const fonts = `'SF Pro Text', 'SF Pro Icons', 'Helvetica Neue', Helvetica, Arial,sans-serif`;

export const style = globalCss({
  ':root': {
    '--fontSize': '22px',
    '--lineHeight': 'calc(var(--fontSize) * 1.5)',
    '--font-family': "'Inter', sans-serif",
    '--font-ascender': '750',
    '--font-descender': '-250',
    '--font-grade': '0',
    '--font-lowercase-height': '500',
    '--font-slant': '0',
    '--font-thin-stroke': '116',
    '--font-weight': '400',
    '--font-width': '100',
  },
  html: {
    '-ms-text-size-adjust': '100%',
    '-webkit-text-size-adjust': '100%',
  },
  body: {
    '-moz-font-feature-settings': 'kern',
    '-webkit-font-smoothing': 'antialiased',
    '-moz-osx-font-smoothing': 'grayscale',
    scrollBehavior: 'smooth',
    tabSize: '4',
    backgroundColor: '$GDSColorPrimaryWhite',
    fontFamily: fonts,
    fontStyle: 'normal',
    lineHeight: '1.47059',
    fontWeight: '400',
    letterSpacing: '-0.022em',
    fontSynthesis: 'none',
    MozFontFeatureSettings: 'kern',
    WebkitFontSmoothing: 'antialiased',
    MozOsxFontSmoothing: 'grayscale',
    color: '#333333',
    scrollPaddingTop: '100px',
  },
});
