name: '⛩️ Component Request'
description: Suggest a new feature or an improvement of an existing one.
labels: ['Component']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

        Do not forget to update the title above to consisely describe the issue.
  - type: checkboxes
    id: previous
    attributes:
      label: Does the component already exist
      description:
      options:
        - label: I confirm that I have checked if the component already exists in any of the Green libraries
          required: true
  - type: dropdown
    id: frameworks
    attributes:
      label: For which framework/library you are requesting the component
      multiple: true
      options:
        - All frameworks
        - React
        - React Charts
        - Angular
        - Angular Charts
        - Chlorophyll
        - extract
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide a clear and concise description of your idea. Consider adding code examples, screenshots, and references to similar components.
    validations:
      required: true
  - type: textarea
    id: audience
    attributes:
      label: Who will benefit from this feature?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
