import { GdsBadge } from './badge'
import figma, { html } from '@figma/code-connect/html'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  'https://www.figma.com/design/56EvebfAdgA7JaDIldZAFK/Green-Design-System?node-id=4780-6005&t=GoP2Nr9edEG4JocW-4',
  {
    props: {
      statusText: figma.string('Status text'),
      variant: figma.enum('Variant', {
        Information: 'information',
        Success: 'success',
        Warning: 'warning',
        Error: 'error',
        Notice: 'notice',
      }),
      icon: figma.boolean('Icon'),
    },
    example: ({
      variant,
      statusText,
    }: {
      variant: string
      statusText: string
    }) => html` <gds-badge variant=${variant}> ${statusText} </gds-badge>`,
  },
)
