export { default as Aside } from './aside/part.aside.core'
export { default as Sidebar } from './part.sidebar'
export { default as Meta } from './part.meta'
export { default as Breadcrumbs } from './part.breadcrumbs'
export { default as Header } from './part.header'
export { default as Search } from './part.search'
export { default as Main } from './part.main'
export { default as Copy } from './part.copy'
