name: Triggered deploy of all storybooks
on:
  workflow_dispatch:
  push:
    branches: [beta]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GREEN_BOT_APP_ID }}
          private-key: ${{ secrets.GREEN_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile --silent

      - name: Get branch name
        shell: bash
        run: echo "branch=${GITHUB_REF}" >> "$GITHUB_OUTPUT"
        id: branch

      - name: Determine deploy target
        shell: bash
        run: |
          if [[ "${{ steps.branch.outputs.branch }}" == "refs/heads/main" ]]; then
            echo "target=latest" >> "$GITHUB_OUTPUT"
          elif [[ "${{ steps.branch.outputs.branch }}" == "refs/heads/alpha" ]]; then
            echo "target=alpha" >> "$GITHUB_OUTPUT"
          elif [[ "${{ steps.branch.outputs.branch }}" == "refs/heads/beta" ]]; then
            echo "target=beta" >> "$GITHUB_OUTPUT"
          else
            echo "target=pr-${{ github.event.number }}" >> "$GITHUB_OUTPUT"
          fi
        id: target

      - name: Build all storybooks
        run: yarn nx run-many --target build-storybook --all --exclude=angular

        ## For some reason, the angular storybook build fails on the run-many command
        ## So as a workaroun, we run it separately
      - name: Build Angular storybook
        run: yarn nx run angular:build-storybook

      - name: Breakpoint if build failed
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: splashdust

      ## This is a index file used by Design Library to show links to components
      - name: Copy designlibrary.json
        run: yarn nx run-many --target copy-designlibrary-json --all

      - name: Deploy storybooks to GitHub Pages

        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ steps.get_token.outputs.token }}
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/storybook # The folder the action should deploy.
          target-folder: ${{ steps.target.outputs.target }} # The folder the action should deploy to.
